### ISSUE TITLE
Test data for rlwimi instruction

### ISSUE THREAD

**Issue by maximumspatium** [lioncash/DolphinPPCTests#3]
First of all, thank you very much for bringing us the PPC tests! They are really helpful when developing a PowerPC emulator.

While integrating the DolphinPPCTests into [DingusPPC](https://github.com/dingusdev/dingusppc) emulator, I've stumbled upon the following problem:

The first test data for the rlwimi instruction in instruction_test_console.txt looks like that:
`RLWIMI   :: rD 0xE00001F9 | rS 0x0000001E | SH 0x00000000 | MB: 0x00000000 | ME: 0x0000000A | XER: 0x00000000 | CR: 0x00000000`

The rlwimi instruction should, according with the above line, produce 0xE00001F9 given rA=0x7FFFFFFF and rS=0x1E, no shift and MASK(mb=0, me=10).

A manual simulation of the rlwimi execution reveals the following:
```
mask = 0xFFE00000;
tmp1 = rA & ~mask = 0x7FFFFFFF & 0x1FFFFF = 0x1FFFFF
tmp2 = rS & mask = 0x0000001E & 0xFFE00000 = 0
rA = tmp1 | tmp2 = 0x1FFFFF | 0 = 0x1FFFFF
```
The result of 0x1FFFFF doesn't match the ground true value 0xE00001F9 generated by HW.

It looks like something is wrong with the test data or with my simulation (triple checked with the Motorola docs, of course).
I also noticed that the ASM statement in the [OPTEST_5_COMPONENTS](https://github.com/lioncash/DolphinPPCTests/blob/53168996df4b0f3d32d94aad53d95fb48a89f2ee/source/Integer.cpp#L80) macro sets the output value like that:
```
: [out]"+&r"(output)
```
while all other macros use `: [out]"=&r"(output)`, that is `=` instead of `+`.

Could you kindly clarify that?

**Comment by maximumspatium** [comment]
Update: I've run a similar test in my iMac G5 and got this:

`rlwimi :: rD 0x001FFFFF | rS 0x0000001E | XER: 0x00000000 | CR: 0x84000002`

Everything as I expected except the CR that shows up an odd value. The code for setting and getting CR on G5 is probably different than in 32bit CPUs.

I believe that the correct output setting in the ASM statement for OPTEST_5_COMPONENTS should be:

`: [out]"+r"(output)`

**Comment by lioncash** [comment]
Hi, sorry for the (very) late response; I must have missed the notification for this.

Thanks for uncovering this issue! I've pushed a fix for it within 2708d1ab7628d69419fb5ef30c2ef0db0161a54e

**Comment by maximumspatium** [comment]
Fine! I want to thank you for your DolphinPPCTests a lot! Sorry for posting into the closed issue. But I think you'd be pleased to hear that your testing framework has helped a lot in developing Dingusppc.
I found out that RLWIx and SRAWI tests in DolphinPPCTests have bugs, too. In order to fix them, I coded all tests from scratch in gcc 3.3 on Mac OS X 10.3 and ran them to produce new test dumps. Here is the updated version: https://github.com/dingusdev/dingusppc/blob/master/cpu/ppc/test/ppcinttest.txt

I can open a new issue for those bugs. Alternatively, we can reopen this issue. Just tell me what you prefer.
Cheers
Max

**Comment by lioncash** [comment]
> I want to thank you for your DolphinPPCTests a lot! Sorry for posting into the closed issue. But I think you'd be pleased to hear that your testing framework has helped a lot in developing Dingusppc.

No problem! I'm glad the tests were useful for projects other than Dolphin 😃

> I can open a new issue for those bugs. Alternatively, we can reopen this issue. Just tell me what you prefer.

I'd prefer a new issue for those if it's not too much trouble. That way the fix(es) can be associated with  own issue number. Thanks again for finding those oversights!.
