### ISSUE TITLE
Missing ADDEO test case

### ISSUE THREAD

**Issue by maximumspatium** [lioncash/DolphinPPCTests#5]
The OV bit in the PowerPC architecture will be set when both rA and rB with the same sign produce a sum with the opposite sign, i.e.

```
if ((rD < 0 && rA >= 0 && rB >= 0) || (rD >= 0 && rA < 0 && rB < 0)) {
    SetOV;
} else {
    ClearOV;
}
```

There must be two tests for those cases:

```
rA = 0x7FFFFFFF, rB = 1, rD = 0x80000000
rA = 0x80000000, rB = 0x80000000, rD = 0
```

The latter is missing in the DolphinPPCTests. There are two identical test cases instead:

https://github.com/lioncash/DolphinPPCTests/blob/2708d1ab7628d69419fb5ef30c2ef0db0161a54e/source/Integer.cpp#L314-L315

I therefore propose to include the following test case:
```
OPTEST_3_COMPONENTS("addeo", 0x80000000, 0x80000000);
```

**Comment by lioncash** [comment]
Added the requested test. Thanks for pointing it out!
