### ISSUE TITLE
Missing ADDIC. tests

### ISSUE THREAD

**Issue by maximumspatium** [lioncash/DolphinPPCTests#6]
As opposite to all other arithmetic PowerPC instructions, the "addic." instruction doesn't follow the common pattern with the RC bit.

It has its own primary opcode 0xD instead.

Unfortunately, DolphinPPCTests doesn't include tests for this instruction. It would be helpful to have tests for it as well.

**Comment by lioncash** [comment]
I've added variants of the tests using the same ADDIC tests for parity. Feel free to let me know if you want specific tests included.
